### ISSUE TITLE
 Guard.NotNullOrWhitespace enforces guard message because of overload

### ISSUE THREAD

**Issue by tomkerkhove** [george-pancescu/Guard#1]
Guard.NotNullOrWhitespace optionally allows you to specify a guard message.

However,  it is being enforced by the compiler because there is an overload which is interfering.

Do you have plans to fix this?

**Comment by george-pancescu** [comment]
Hi Tom,

Thank you for pointing this out! I fixed the issue and released a new version of the Nuget package (https://www.nuget.org/packages/Guard.NET/1.0.0.1).

**Comment by tomkerkhove** [comment]
Awesome, thank you!
