### ISSUE TITLE
Guard.NotNull enforces guard message because of overload

### ISSUE THREAD

**Issue by tomkerkhove** [george-pancescu/Guard#3]
Guard.NotNull optionally allows you to specify a guard message.

However, it is being enforced by the compiler because there is an overload which is interfering.

Do you have plans to fix this?

**Comment by george-pancescu** [comment]
Fixed (as well as for all the other methods). Thanks!
Released a new version of the Nuget package (https://www.nuget.org/packages/Guard.NET/1.0.0.2).

**Comment by tomkerkhove** [comment]
Awesome, thanks for the quick fix!
