### ISSUE TITLE
Add .NET Standard 2.0 support

### ISSUE THREAD

**Issue by GioAbq** [george-pancescu/Guard#8]
Hi, currently not all platforms support .NET 5 - Xamarin for example. Can you add .NET Standard 2.0 support?

**Comment by george-pancescu** [comment]
Hi,

You can use **[Guard.NET 1.2.0](https://www.nuget.org/packages/Guard.NET/1.2.0)**, which has support for .NET Standard 2.0, and can be used for older frameworks

Versions following 2.0.0 will only target .NET 5, as per Microsoft's recommendation for code sharing.
